//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCuoiki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectCuoiKiEntities : DbContext
    {
        public ProjectCuoiKiEntities()
            : base("name=ProjectCuoiKiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<footer> footers { get; set; }
        public DbSet<imageProduct> imageProducts { get; set; }
        public DbSet<menu> menus { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<positionbanner> positionbanners { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<slideshow> slideshows { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<typeproduct> typeproducts { get; set; }
        public DbSet<banner> banners { get; set; }
    }
}
