//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCuoiki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectCuoiKiEntities : DbContext
    {
        public ProjectCuoiKiEntities()
            : base("name=ProjectCuoiKiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<footer> footers { get; set; }
        public virtual DbSet<imageProduct> imageProducts { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<positionbanner> positionbanners { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<slideshow> slideshows { get; set; }
        public virtual DbSet<typeproduct> typeproducts { get; set; }
        public virtual DbSet<userAccount> userAccounts { get; set; }
        public virtual DbSet<userRole> userRoles { get; set; }
        public virtual DbSet<banner> banners { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Sp_Account_Login(string userName, string passWord)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("passWord", passWord) :
                new ObjectParameter("passWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Account_Login", userNameParameter, passWordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> userValid(string userName, string passWord)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("passWord", passWord) :
                new ObjectParameter("passWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("userValid", userNameParameter, passWordParameter);
        }
    }
}
