//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCuoiki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class positionbanner
    {
        public positionbanner()
        {
            this.banners = new HashSet<banner>();
        }
    
        public int positionId { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<banner> banners { get; set; }
    }
}
